site_name: Clinical Quality Framework
site_url: https://www.cqframework.org/
site_author: Smile Digital Health
site_description: >-
  Homepage for the Clinical Quality Framework (CQF) effort

copyright: Copyright &copy; 2022 Smile Digital Health

repo_url: https://github.com/cqframework/cqframework.github.io
repo_name: CQFramework Homepage


theme:
  favicon: assets/images/icon/favicon.ico

  logo: assets/images/logo.svg
  name: material
  palette:
    scheme: default
    primary: white
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

nav:
  - Home: index.md
  - Projects: projects.md


